package model;
// Generated Jun 3, 2017 10:54:16 PM by Hibernate Tools 4.3.1



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer uid;
     private String itemName;
     private String itemCategory;
     private int itemPrice;
     private int itemCost;
     private int restaurantUid;
     private int minimumQuantity;
     private int quantity;

    public Item() {
    }

    public Item(String itemName, String itemCategory, int itemPrice, int itemCost, int restaurantUid, int minimumQuantity, int quantity) {
       this.itemName = itemName;
       this.itemCategory = itemCategory;
       this.itemPrice = itemPrice;
       this.itemCost = itemCost;
       this.restaurantUid = restaurantUid;
       this.minimumQuantity = minimumQuantity;
       this.quantity = quantity;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }
    public int getItemPrice() {
        return this.itemPrice;
    }
    
    public void setItemPrice(int itemPrice) {
        this.itemPrice = itemPrice;
    }
    public int getItemCost() {
        return this.itemCost;
    }
    
    public void setItemCost(int itemCost) {
        this.itemCost = itemCost;
    }
    public int getRestaurantUid() {
        return this.restaurantUid;
    }
    
    public void setRestaurantUid(int restaurantUid) {
        this.restaurantUid = restaurantUid;
    }
    public int getMinimumQuantity() {
        return this.minimumQuantity;
    }
    
    public void setMinimumQuantity(int minimumQuantity) {
        this.minimumQuantity = minimumQuantity;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


