package model;
// Generated Jun 3, 2017 10:54:16 PM by Hibernate Tools 4.3.1



/**
 * Restaurant generated by hbm2java
 */
public class Restaurant  implements java.io.Serializable {


     private Integer restaurantUid;
     private String name;
     private String currency;

    public Restaurant() {
    }

    public Restaurant(String name, String currency) {
       this.name = name;
       this.currency = currency;
    }
   
    public Integer getRestaurantUid() {
        return this.restaurantUid;
    }
    
    public void setRestaurantUid(Integer restaurantUid) {
        this.restaurantUid = restaurantUid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }




}


