package model;
// Generated Jun 3, 2017 10:54:16 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer uid;
     private String email;
     private String username;
     private String password;
     private String phonenumber;
     private String accessright;
     private int restaurantUid;

    public User() {
    }

    public User(String email, String username, String password, String phonenumber, String accessright, int restaurantUid) {
       this.email = email;
       this.username = username;
       this.password = password;
       this.phonenumber = phonenumber;
       this.accessright = accessright;
       this.restaurantUid = restaurantUid;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public String getAccessright() {
        return this.accessright;
    }
    
    public void setAccessright(String accessright) {
        this.accessright = accessright;
    }
    public int getRestaurantUid() {
        return this.restaurantUid;
    }
    
    public void setRestaurantUid(int restaurantUid) {
        this.restaurantUid = restaurantUid;
    }




}


